FROM debian:stretch

# Install tools, utilities and osm2pgsql
RUN set -x && \
    DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y --no-install-recommends osm2pgsql postgresql-client && \
    rm -rf /var/lib/apt/lists/*

COPY openstreetmap-carto.style /

RUN mkdir -p /openstreetmap-carto
WORKDIR /openstreetmap-carto

CMD sh scripts/docker-startup.sh import
