FROM debian:stretch

RUN apt-get update && apt-get install --no-install-recommends -y \
    curl ca-certificates osm2pgsql postgresql-client \
    && rm -rf /var/lib/apt/lists/*

ADD openstreetmap-carto.style /

RUN mkdir -p /openstreetmap-carto
WORKDIR /openstreetmap-carto

CMD psql -c "SELECT 1 FROM pg_database WHERE datname = 'gis';" | grep -q 1 || createdb gis && \
    psql -d gis -c 'CREATE EXTENSION IF NOT EXISTS postgis;' && \
    psql -d gis -c 'CREATE EXTENSION IF NOT EXISTS hstore;' && \
    osm2pgsql \
    --cache $OSM2PGSQL_CACHE \
    --number-processes $OSM2PGSQL_NUMPROC \
    --hstore \
    --multi-geometry \
    --database gis \
    --style openstreetmap-carto.style \
    --tag-transform-script openstreetmap-carto.lua \
    $OSM2PGSQL_DATAFILE
