DROP VIEW IF EXISTS planet_osm_polygon;
CREATE VIEW planet_osm_polygon AS
SELECT
osm_id,
tags->'access' as "access",
tags->'addr:housename' as "addr:housename",
tags->'addr:housenumber' as "addr:housenumber",
tags->'admin_level' as "admin_level",
tags->'aerialway' as "aerialway",
tags->'aeroway' as "aeroway",
tags->'amenity' as "amenity",
tags->'barrier' as "barrier",
tags->'bicycle' as "bicycle",
tags->'boundary' as "boundary",
tags->'bridge' as "bridge",
tags->'building' as "building",
tags->'denomination' as "denomination",
tags->'generator:source' as "generator:source",
tags->'highway' as "highway",
tags->'historic' as "historic",
tags->'iata' as "iata",
tags->'landuse' as "landuse",
tags->'layer' as "layer",
tags->'leaf_type' as "leaf_type",
tags->'leisure' as "leisure",
tags->'man_made' as "man_made",
tags->'military' as "military",
tags->'name' as "name",
tags->'name:de' as "name:de",
tags->'int_name' as "int_name",  
tags->'name:en' as "name:en",
tags->'natural' as "natural",
tags->'operator' as "operator",
tags->'place' as "place",
tags->'power' as "power",
tags->'power_source' as "power_source",
tags->'railway' as "railway",
tags->'ref' as "ref",
tags->'religion' as "religion",
tags->'ruins' as "ruins",
tags->'shop' as "shop",
tags->'sport' as "sport",
tags->'surface' as "surface",
tags->'tourism' as "tourism",
tags->'waterway' as "waterway",
tags->'wetland' as "wetland",
osm_tag2num(tags->'width') as "num_width",
way as "way",
way_area as way_area,
z_order as z_order,
osml10n_get_placename_from_tags(tags,true,false,chr(10),'de',way) as localized_name_second,
osml10n_get_placename_from_tags(tags,false,false,chr(10),'de',way) as localized_name_first,
osml10n_get_name_without_brackets_from_tags(tags,'de',way) as localized_name_without_brackets,
osml10n_get_streetname_from_tags(tags,true,false,chr(10),'de', way) as localized_streetname,
osml10n_get_country_name(tags,chr(10),'de') as country_name,
COALESCE(tags->'name:hsb',tags->'name:de',tags->'name') as name_hrb,
tags as "tags"
FROM planet_osm_hstore_polygon;

GRANT select ON planet_osm_polygon TO public;
