DROP VIEW IF EXISTS planet_osm_line;
CREATE VIEW planet_osm_line AS
SELECT
osm_id,
tags->'access' as "access",
tags->'addr:interpolation' as "addr:interpolation",
tags->'aerialway' as "aerialway",
tags->'aeroway' as "aeroway",
tags->'barrier' as "barrier",
tags->'building' as "building",
tags->'bicycle' as "bicycle",
tags->'bridge' as "bridge",
tags->'construction' as "construction",
tags->'covered' as "covered",
tags->'culvert' as "culvert",
tags->'disused' as "disused",
tags->'embankment' as "embankment",
tags->'foot' as "foot",
tags->'highway' as "highway",
tags->'historic' as "historic",
tags->'horse' as "horse",
tags->'intermittent' as "intermittent",
tags->'junction' as "junction",
tags->'layer' as "layer",
tags->'lock' as "lock",
tags->'man_made' as "man_made",
tags->'name' as "name",
tags->'name:de' as "name:de",
tags->'int_name' as "int_name",  
tags->'name:en' as "name:en",
tags->'natural' as "natural",
tags->'oneway' as "oneway",
tags->'operator' as "operator",
tags->'power' as "power",
tags->'proposed' as "proposed",
tags->'railway' as "railway",
tags->'ref' as "ref",
tags->'route' as "route",
tags->'service' as "service",
tags->'surface' as "surface",
tags->'tracktype' as "tracktype",
tags->'tunnel' as "tunnel",
tags->'waterway' as "waterway",
tags->'width' as "width",
osm_tag2num(tags->'width') as "num_width",
way as "way",
way_area as way_area,
z_order as z_order,
osml10n_get_placename(tags->'name',tags->'name:de',tags->'int_name',tags->'name:en', true, way) as localized_name_inside_brackets,
osml10n_get_placename(tags->'name',tags->'name:de',tags->'int_name',tags->'name:en', false, way) as localized_name_outside_brackets,
osml10n_get_name_without_brackets(tags->'name',tags->'name:de',tags->'int_name',tags->'name:en', way) as localized_name_without_brackets,
osml10n_get_streetname(tags->'name',tags->'name:de',tags->'int_name',tags->'name:en', true, 'de', way) as localized_streetname_inside_brackets,
osml10n_get_streetname(tags->'name',tags->'name:de',tags->'int_name',tags->'name:en', false, 'de', way) as localized_streetname_outside_brackets,
tags as tags
FROM planet_osm_hstore_line;

GRANT select ON planet_osm_line to public;
