DROP VIEW IF EXISTS view_osmde_carto_line;
CREATE VIEW view_osmde_carto_line AS
SELECT
osm_id,
tags->'access' as "access",
tags->'addr:housename' as "addr:housename",
tags->'addr:housenumber' as "addr:housenumber",
tags->'addr:interpolation' as "addr:interpolation",
tags->'admin_level' as "admin_level",
tags->'aerialway' as "aerialway",
tags->'aeroway' as "aeroway",
tags->'amenity' as "amenity",
tags->'barrier' as "barrier",
tags->'bicycle' as "bicycle",
tags->'boundary' as "boundary",
tags->'brand' as "brand",
tags->'bridge' as "bridge",
tags->'building' as "building",
tags->'capital' as "capital",
tags->'construction' as "construction",
tags->'covered' as "covered",
tags->'culvert' as "culvert",
tags->'cutting' as "cutting",
tags->'denomination' as "denomination",
tags->'disused' as "disused",
tags->'embankment' as "embankment",
tags->'foot' as "foot",
tags->'generator:source' as "generator:source",
tags->'harbour' as "harbour",
tags->'highway' as "highway",
tags->'historic' as "historic",
tags->'horse' as "horse",
tags->'intermittent' as "intermittent",
tags->'junction' as "junction",
tags->'landuse' as "landuse",
tags->'layer' as "layer",
tags->'leisure' as "leisure",
tags->'lock' as "lock",
tags->'man_made' as "man_made",
tags->'military' as "military",
tags->'motorcar' as "motorcar",
tags->'motorroad' as "motorroad",
tags->'name' as "name",
tags->'name:de' as "name:de",
tags->'int_name' as "int_name",  
tags->'name:en' as "name:en",
tags->'natural' as "natural",
tags->'oneway' as "oneway",
tags->'operator' as "operator",
tags->'place' as "place",
tags->'poi' as "poi",
tags->'population' as "population",
tags->'power' as "power",
tags->'power_source' as "power_source",
tags->'proposed' as "proposed",
tags->'railway' as "railway",
tags->'ref' as "ref",
tags->'religion' as "religion",
tags->'route' as "route",
tags->'service' as "service",
tags->'shop' as "shop",
tags->'sport' as "sport",
tags->'surface' as "surface",
tags->'toll' as "toll",
tags->'tourism' as "tourism",
tags->'tower:type' as "tower:type",
tags->'tracktype' as "tracktype",
tags->'tunnel' as "tunnel",
tags->'water' as "water",
tags->'waterway' as "waterway",
tags->'wetland' as "wetland",
tags->'width' as "width",
osm_tag2num(tags->'width') as "num_width",
tags->'wood' as "wood",
way as "way",
way_area as way_area,
z_order as z_order,
osml10n_get_placename(tags->'name',tags->'name:de',tags->'int_name',tags->'name:en', true, way) as localized_name_inside_brackets,
osml10n_get_placename(tags->'name',tags->'name:de',tags->'int_name',tags->'name:en', false, way) as localized_name_outside_brackets,
osml10n_get_name_without_brackets(tags->'name',tags->'name:de',tags->'int_name',tags->'name:en', way) as localized_name_without_brackets,
osml10n_get_streetname(tags->'name',tags->'name:de',tags->'int_name',tags->'name:en', true, 'de', way) as localized_streetname_inside_brackets,
osml10n_get_streetname(tags->'name',tags->'name:de',tags->'int_name',tags->'name:en', false, 'de', way) as localized_streetname_outside_brackets,
tags as tags
FROM planet_osm_line;

GRANT select ON view_osmde_carto_line to public;
