all: wood_mixed.png wood_coniferous.png wood_deciduous.png

wood_mixed.png: wood_mixed.png
	inkscape -e wood_mixed.png wood_mixed.svg
	
wood_coniferous.png: wood_coniferous.png
	inkscape -e wood_coniferous.png wood_coniferous.svg
	
wood_deciduous.png: wood_deciduous.png
	inkscape -e wood_deciduous.png wood_deciduous.svg

clean:
	rm wood*.png
