#!/bin/bash -e

# A simple script that generates the standard road shields.
# Run from the same directory as create_shield
# Copyright 2014 Paul Norman
# Released under the Creative Commons CC0 license

widths='
1:18
2:25.25
3:32.5
4:39
5:46
6:52.5
7:59.25
8:66
9:70.5
10:75.75
11:80.75'

#shield colors were generated with scripts/generate_road_colors.py
colours='motorway:#d18996
trunk:#da9b88
primary:#d5b284
secondary:#c6ca90
tertiary:#c6c6c6'

#motorway: lch(65, 30, 10) Conversion error on moving from lch to rgb: 0.4 lch(-0.3, -0.4, -0.9)
#trunk: lch(70, 30, 42) Conversion error on moving from lch to rgb: 0.8 lch(-0.3, -1.4, 1.1)
#primary: lch(75, 30, 74) Conversion error on moving from lch to rgb: 1.7 lch(-0.3, -0.8, 3.9)
#secondary: lch(80, 30, 106) Conversion error on moving from lch to rgb: 1.7 lch(-0.2, 0.7, 4.3)
#tertiary: lch(80, 0, 0) Conversion error on moving from lch to rgb: 0.0 lch(-0.0, 0.0, 322.5)



xoffset=1.25
yoffset=1.75

heights='
1:18
2:30
3:44
4:54'

for h in $heights; do
  for w in $widths; do
    xchars=$(echo $w | awk -F ":" '{print $1}')
    xpixels=$(echo $w | awk -F ":" '{print $2}')
    ychars=$(echo $h | awk -F ":" '{print $1}')
    ypixels=$(echo $h | awk -F ":" '{print $2}')
    for shield in $colours; do
      class=$(echo $shield | awk -F ":" '{print $1}')
      colour=$(echo $shield | awk -F ":" '{print $2}')
      ./create_shield $colour $xpixels $ypixels $xoffset $yoffset > "${class}_${xchars}x${ychars}.svg"
    done;
  done;
done;
