#!/bin/sh -e

# A simple script to generate a SVG road shield.
# Copyright 2014 Paul Norman
# Released under the Creative Commons CC0 license

# Syntax
# ./create_shield colour width height xoffset yoffset

# Fixed values
RADIUS=9
OUTERLINE=1.5
WHITELINE=1.5

COLOUR=$1
WIDTH=$2
HEIGHT=$3
XOFFSET=$4
YOFFSET=$5


echo "<svg xmlns='http://www.w3.org/2000/svg' width='100%' height='100%' "\
"viewBox='0 0 $(echo $WIDTH + $XOFFSET | bc -q) $(echo $HEIGHT + $YOFFSET | bc -q)'>"
echo "<rect x='$XOFFSET' y='$YOFFSET' height='$HEIGHT' width='$WIDTH' rx='$RADIUS' fill='$COLOUR'/>"

echo "<rect x='$(echo $XOFFSET + $OUTERLINE | bc -q)' y='$(echo $YOFFSET + $OUTERLINE | bc -q)' "\
"height='$(echo $HEIGHT - 2\*$OUTERLINE | bc -q)' width='$(ECHO $WIDTH - 2\*$OUTERLINE | bc -q)' "\
"rx='$(echo $RADIUS - $OUTERLINE | bc -q)' fill='white'/>"

echo "<rect x='$(echo $XOFFSET + $OUTERLINE + $WHITELINE | bc -q)' y='$(echo $YOFFSET + $OUTERLINE + $WHITELINE| bc -q)' "\
"height='$(echo $HEIGHT - 2\*$OUTERLINE - 2\*$WHITELINE | bc -q)' width='$(ECHO $WIDTH - 2\*$OUTERLINE - 2\*$WHITELINE | bc -q)' "\
"rx='$(echo $RADIUS - $OUTERLINE - $WHITELINE | bc -q)' fill='$COLOUR'/>"
echo "</svg>"
